### ISSUE TITLE
Web page connection - 302 error code 

### ISSUE THREAD

**Issue by bbenjamin11** [robertsLando/Zwave2Mqtt#20]
After the success install, I'm connect on the web service : http://myLocalIP:8091

But, my client notify me than the page is not redirected correctly.

In the backend, I have this message : 
```
  z2m:Store settings.json not found +0ms
  z2m:Store scenes.json not found +109ms
  z2m:App Application path:/usr/src/app +0ms
  z2m:Gateway Gateway needs both MQTT and Zwave Configuration to work +0ms
  z2m:App Listening on port 8091 +0ms
  z2m:App Error: Not Found
  z2m:App     at /snapshot/Zwave2Mqtt/app.js:0:0
  z2m:App     at Layer.handle [as handle_request] (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/layer.js:95:5)
  z2m:App     at trim_prefix (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:317:13)
  z2m:App     at /snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:284:7
  z2m:App     at Function.process_params (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:335:12)
  z2m:App     at next (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:275:10)
  z2m:App     at cors (/snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:188:7)
  z2m:App     at /snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:224:17
  z2m:App     at originCallback (/snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:214:15)
  z2m:App     at /snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:219:13
  z2m:App     at optionsCallback (/snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:199:9)
  z2m:App     at corsMiddleware (/snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:204:7)
  z2m:App     at Layer.handle [as handle_request] (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/layer.js:95:5)
  z2m:App     at trim_prefix (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:317:13)
  z2m:App     at /snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:284:7
  z2m:App     at Function.process_params (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:335:12) +9s
GET / 302 163.416 ms - 46
  z2m:App Error: Not Found
  z2m:App     at /snapshot/Zwave2Mqtt/app.js:0:0
  z2m:App     at Layer.handle [as handle_request] (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/layer.js:95:5)
...
...
...
  z2m:App Error: Not Found
  z2m:App     at /snapshot/Zwave2Mqtt/app.js:0:0
  z2m:App     at Layer.handle [as handle_request] (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/layer.js:95:5)
  z2m:App     at trim_prefix (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:317:13)
  z2m:App     at /snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:284:7
  z2m:App     at Function.process_params (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:335:12)
  z2m:App     at next (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:275:10)
  z2m:App     at cors (/snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:188:7)
  z2m:App     at /snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:224:17
  z2m:App     at originCallback (/snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:214:15)
  z2m:App     at /snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:219:13
  z2m:App     at optionsCallback (/snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:199:9)
  z2m:App     at corsMiddleware (/snapshot/Zwave2Mqtt/node_modules/cors/lib/index.js:204:7)
  z2m:App     at Layer.handle [as handle_request] (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/layer.js:95:5)
  z2m:App     at trim_prefix (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:317:13)
  z2m:App     at /snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:284:7
  z2m:App     at Function.process_params (/snapshot/Zwave2Mqtt/node_modules/express/lib/router/index.js:335:12) +64ms
GET / 302 39.646 ms - 46

```

To inform, I use one Raspberry pi 0w with raspbian-strech. I have try your dockers images, the classic install and build my own docker image (with arm32v6/alpine). 

Thanks a lot for your help !

**Comment by robertsLando** [comment]
I need to investigate, tomorrow I will do some checks. So just to know did you tried also to build the project yourself (by cloning git repo and running npm build) or did you just pulled the precompiled image from dockerhub?
 thanks for the feedback. 

Daniel

**Comment by bbenjamin11** [comment]
Hi, thanks for your help.

I have try your all docker image form docker-hub without success. So I have try with your repo to build the app (npm install). And to finish, clone your Zwave2mqtt-docker and build from this source. 

All installs went well but none worked properly on my Rpi0w.

Thanks,
Benjamin

**Comment by robertsLando** [comment]
I have just successfully installed it on my Rpi 3 Model B+ following the "manual" install:

```bash
# Install Openzwave
wget "https://github.com/ekarak/openzwave-debs-raspbian/raw/master/v1.4.79/openzwave_1.4.79.gfaea7dd_armhf.deb"
wget "https://github.com/ekarak/openzwave-debs-raspbian/raw/master/v1.4.79/libopenzwave1.3_1.4.79.gfaea7dd_armhf.deb"
wget "https://github.com/ekarak/openzwave-debs-raspbian/raw/master/v1.4.79/libopenzwave1.3-dev_1.4.79.gfaea7dd_armhf.deb"
sudo dpkg -i *openzwave*.deb
export LD_LIBRARY_PATH=/usr/local/lib
sudo sed -i '$a LD_LIBRARY_PATH=/usr/local/lib' /etc/environment
sudo ldconfig

# Clone and build app
git clone https://github.com/robertsLando/Zwave2Mqtt.git
cd Zwave2Mqtt
npm install
npm run build

# Start app
npm start
```

I have also tried with docker and it works: 

```bash
pi@raspberrypi:~ $ sudo docker run --rm -it -p 8091:8091 --device=/dev/ttyACM0 --mount source=zwave2mqtt,target=/usr/src/app robertslando/zwave2mqtt:arm32v7-latest
Unable to find image 'robertslando/zwave2mqtt:arm32v7-latest' locally
arm32v7-latest: Pulling from robertslando/zwave2mqtt
d8d287cbc574: Pull complete 
74af0ebc085c: Pull complete 
6e873d5f914a: Pull complete 
a2075eca02a7: Pull complete 
b409dfb16e6e: Pull complete 
58aa07503bf7: Pull complete 
Digest: sha256:2175669ef69d5ede28b0a0a20799b78feae6b05bbd6bf79cb666edefe91b56bd
Status: Downloaded newer image for robertslando/zwave2mqtt:arm32v7-latest
  z2m:Store settings.json not found +0ms
  z2m:Store scenes.json not found +10ms
  z2m:App Application path:/usr/src/app +0ms
  z2m:Gateway Gateway needs both MQTT and Zwave Configuration to work +0ms
  z2m:App Listening on port 8091 +0ms
GET / 200 21.211 ms - 1432
GET /static/js/manifest.2ae2e69a05c33dfc65f8.js 200 12.001 ms - 857
GET /static/css/app.6767e8280089a963b7ff2532eaea9424.css 200 12.656 ms - 210253
GET /static/js/app.dd547788f2afe0892d2a.js 200 10.006 ms - 49171
GET /static/js/vendor.bdbd6d4fd3cc9baa1adb.js 200 13.290 ms - 812044
GET /static/logo.png 200 7.817 ms - 10014
  z2m:App New connection xlmDmozEgQJ7b3hbAAAA +4s
GET /static/favicons/favicon-32x32.png 200 7.778 ms - 1831
```

I don't have a Pi0w to test this but if it doesn't work using docker it must work by compiling the library yourself (first method I show you there, maybe you would need to compile openzwave yourself too) 

Let me know

**Comment by robertsLando** [comment]
I have also add a commit to better handle logs of `404 Not Found` errors. Anyway you receive 302 because I redirect by default all 404 to /. I think you forgot to run the command `npm run build` and it doesn't find any `index.html` file in `/dist` folder

**Comment by bbenjamin11** [comment]
I have remove the volume and the image, repull the image, recreate the volume and it work !

Thanks for your help !!
See you,
Benjamin.
